name: Manter App Acordado
on:
  schedule:
    - cron: '0 */4 * * *' # Executa a cada 4 horas
  workflow_dispatch:      # Permite que você force o teste manualmente
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping URL
        run: curl -s -o /dev/null -w "%{http_code}\n" https://viaprev.streamlit.app/
